<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PaqueteriaWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PaqueteriaWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PaqueteriaWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://Paqueteria/">
    <import location="http://localhost:18080/Paqueteria/Paqueteria?WSDL" namespace="http://Paqueteria/"/>
    <plnk:partnerLinkType name="PaqueteriaLinkType">
        <plnk:role name="PaqueteriaRole" portType="ns:Paqueteria"/>
    </plnk:partnerLinkType>
</definitions>
