<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PagosWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PagosWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PagosWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://Pagos/">
    <import location="http://localhost:18080/Pagos/Pagos?WSDL" namespace="http://Pagos/"/>
    <plnk:partnerLinkType name="PagosLinkType">
        <plnk:role name="PagosRole" portType="ns:Pagos"/>
    </plnk:partnerLinkType>
</definitions>
